"""
mcp/ — Gold Tier MCP (Model Context Protocol) multi-server package.

Modules
-------
registry.py                  Tool registry: action_type → handler, plus DRY_RUN flag.
router.py                    Dispatcher: routes action_type → registered stub handler.
email_mcp_stub.py            Email send + external notification stubs.
browser_mcp_stub.py          Browser automation, payment, deploy, delete, publish stubs.
calendar_mcp_stub.py         Google Calendar event creation stub.
gmail_mcp_server.py          Gmail MCP server: draft_email, send_email, search_email.
gmail_oauth.py               OAuth2 credential loader / Gmail service builder.
playwright_browser_server.py Playwright browser: open_url, click_selector, type_text, screenshot.
odoo_mcp_stub.py             Odoo JSON-RPC: odoo_create_partner, odoo_create_invoice, odoo_list_invoices.
social_mcp_stub.py           Social Media (cloud-simulated): Facebook, Instagram, Twitter/X.
                             NOTE: Live mode permanently blocked (social_safety_gate).
                             DRY_RUN=true → dry_run_logged | DRY_RUN=false → blocked_live_mode.

Registered action_types
-----------------------
    email_send              → email_mcp_stub
    notify_external         → email_mcp_stub
    send_email              → gmail_mcp_server   (overrides email_mcp_stub alias)
    draft_email             → gmail_mcp_server
    search_email            → gmail_mcp_server
    browser_action          → browser_mcp_stub
    browser_navigate_click  → browser_mcp_stub
    authorize               → browser_mcp_stub
    publish                 → browser_mcp_stub
    deploy                  → browser_mcp_stub
    delete                  → browser_mcp_stub
    payment                 → browser_mcp_stub
    create_calendar_event   → calendar_mcp_stub
    open_url                → playwright_browser_server
    click_selector          → playwright_browser_server
    type_text               → playwright_browser_server
    screenshot              → playwright_browser_server
    odoo_create_partner     → odoo_mcp_stub
    odoo_create_invoice     → odoo_mcp_stub
    odoo_list_invoices      → odoo_mcp_stub
    social_post_facebook    → social_mcp_stub   (dry_run_logged | blocked_live_mode)
    social_post_instagram   → social_mcp_stub   (dry_run_logged | blocked_live_mode)
    social_post_twitter     → social_mcp_stub   (dry_run_logged | blocked_live_mode)
    social_get_analytics    → social_mcp_stub   (dry_run_logged | blocked_live_mode)

Quick usage
-----------
    from mcp.router import dispatch_action

    # Draft an email (DRY_RUN=true by default — logs intent only)
    result = dispatch_action("draft_email", {
        "to":        "manager@company.com",
        "subject":   "Weekly Report",
        "body":      "Please see the attached summary.",
        "task_file": "weekly_report.md",
    })

    # Social media post (safe: always cloud-simulated, live mode permanently blocked)
    result = dispatch_action("social_post_twitter", {
        "text":      "Exciting news from our Q1 launch! #GoldTier #AI",
        "task_file": "social_campaign.md",
    })

    # Retrieve simulated analytics for all platforms
    result = dispatch_action("social_get_analytics", {
        "platform":  "all",
        "period":    "30d",
        "task_file": "monthly_report.md",
    })

    # Search inbox
    result = dispatch_action("search_email", {
        "query": "from:client@example.com is:unread",
    })

Environment
-----------
    MCP_DRY_RUN=false           Enable real actions for non-social stubs (default: true).
    GMAIL_CREDENTIALS_PATH=...  Path to credentials.json (OAuth2 client secret).
    GMAIL_TOKEN_PATH=...        Path to token.json (generated by generate_gmail_token.py).

    Social credentials (documented only — social stub never reads these at runtime):
    FACEBOOK_PAGE_TOKEN=...     Meta Graph API page-level access token.
    FACEBOOK_PAGE_ID=...        Numeric Facebook Page ID.
    INSTAGRAM_ACCESS_TOKEN=...  Instagram Business account token.
    INSTAGRAM_ACCOUNT_ID=...    Instagram Business account ID.
    TWITTER_API_KEY=...         Twitter/X OAuth1.0a consumer key.
    TWITTER_API_SECRET=...      Twitter/X OAuth1.0a consumer secret.
    TWITTER_ACCESS_TOKEN=...    Twitter/X OAuth1.0a access token.
    TWITTER_ACCESS_SECRET=...   Twitter/X OAuth1.0a access token secret.

Gmail setup:   see docs/GMAIL_SETUP.md
Odoo setup:    see docs/ODOO_SETUP.md
Social setup:  see docs/SOCIAL_SETUP.md
"""
